#!/bin/bash

if [[ $1 == "all" ]]; then
    ./run_tests parse ./test_input/parser
    echo
    ./run_tests testc ./test_input
    exit
fi

command="cargo run --bin $1"
[[ $# == 2 ]] && test_dir=$2 || test_dir="test_input"

results=

for i in $test_dir/*.test
do
    result="?"    

    $($command < $i &> /dev/null)
   
    [[ $? == 0 ]] && result="." || result="F"
    echo $result $i
    results=$results$result
done

echo
echo ===============================================================================
echo $results