#!/bin/bash

command="cargo run --bin $1"
[[ $# == 2 ]] && test_dir=$2 || test_dir="test_input"

results=

for i in $test_dir/*.test
do
    result="?"    

    $($command < $i &> /dev/null)
   
    [[ $? == 0 ]] && result="." || result="F"
    echo $result $i
    results=$results$result
done

echo -------------------------------------------------------------------------------
echo $results